### ISSUE TITLE
Exception is thrown when creating WCF Response Object

### ISSUE THREAD

**Issue by shahnhogan** [RasicN/random-test-values#14]
![image](https://cloud.githubusercontent.com/assets/6577320/19242156/9a31caac-8ed7-11e6-933f-e821dd99e92e.png)

There is an exception when creating a WCF response object.

**Comment by RasicN** [comment]
I will look into this. In the meantime I would new the object up and
manually populate the random values.

Thanks!

**Comment by shahnhogan** [comment]
Ok, thanks.

**Comment by RasicN** [comment]
Got a working fix for this will push up after I make sure its not causing any side effects.

**Comment by RasicN** [comment]
Fix should be in v2.0.5, sorry it took so long!
