### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Sobieck00** [RasicN/random-test-values#2]
This repo doesn't have a license associated with it. It would be good to add an MIT License if you want anyone to modify, use it, etc. for any reason. Here is a sample MIT license associated with one of my repos: [MIT License](https://github.com/Sobieck00/practice/blob/master/LICENSE)

**Comment by RasicN** [comment]
Awesome!  You the man.

**Comment by RasicN** [comment]
LICENSE added.
