### ISSUE TITLE
Convert project to .netstandard

### ISSUE THREAD

**Issue by Sobieck** [RasicN/random-test-values#24]
I think it would be great for this project to be a .netstandard project so we don't have to maintain a bunch of different versions for different frameworks.

**Comment by Sobieck** [comment]
This should be closed now.

**Comment by RasicN** [comment]
Found out this has a fit if you have JustMock installed and the profiler turned on.  See ticket with Telerik here: http://www.telerik.com/forums/coreclr-compatibility-issue#wziZMXy2KEWoqcUT6f-RTw
