### ISSUE TITLE
IEnumberable<T> ICollection<T> etc need to be implemented

### ISSUE THREAD

**Issue by Sobieck00** [RasicN/random-test-values#5]
We need to implement collections before the object method is production ready.

**Comment by RasicN** [comment]
Working on this... It is proving to be quite difficult

**Comment by RasicN** [comment]
I think I have something working for ICollection<>, Collection<>, IList<>, List<>.  I will update in a in about 2 hours or so... (lunch :) )

**Comment by Sobieck00** [comment]
Awesome. I'll work on this some this weekend. I was thinking about trying to get ICollection<Object> working.

**Comment by RasicN** [comment]
It should be. Check the read me for supported collection types. Although
I'm sure the code could be improved.

**Comment by Sobieck00** [comment]
I did some work on this. IEnumerable is now up and running and every other class is based on it. We can also recurse over all the supported collection types (I think). I'm still not entirely satisfied with the way we are using a ton of if/if else branches. But, it is functional right now. I worked for a long time trying to figure out a better way... but came up with nothing.
