### ISSUE TITLE
.Net Framework no more supported

### ISSUE THREAD

**Issue by DCourtel** [RasicN/random-test-values#56]
Recent Nuget packages of this project don’t support .Net Framework anymore. Can you make this library supported on .Net Framework 4.8 which is still supported by Microsoft?

Thanks.

**Comment by RasicN** [comment]
Gonna need you to be more specific on what is not working. I have just created a Framework 4.8 console app and it runs just fine. The package is .net standard 2.0 which supports back to 4.6.1.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

![image](https://user-images.githubusercontent.com/21132694/170720314-c2d2a763-0b5b-477f-9ea0-91236279b1a6.png)

```csharp
 internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"Int: {RandomValue.Int()}");
            Console.WriteLine($"String: {RandomValue.String()}");
            Console.WriteLine($"Date: {RandomValue.DateTime()}");

            Console.ReadLine();
        }

    }
```
![image](https://user-images.githubusercontent.com/21132694/170720433-a005b613-2843-4c36-a934-9e1118f2e484.png)

**Comment by DCourtel** [comment]
Sorry, I didn’t know that .net standard 2.0 did support .Net Framework.

**Comment by RasicN** [comment]
So did you just assume it didn't work???

**Comment by DCourtel** [comment]
![image](https://user-images.githubusercontent.com/13787283/170811507-5afe4739-ba67-4749-ad27-425aa96e50ae.png)
