### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by Sobieck00** [RasicN/random-test-values#8]
Do you want me to make pull request just whenever I have a good stopping point? Or should I wait until I'm done doing everything I plan on doing for a few days?

**Comment by RasicN** [comment]
I don't know. This (open source) is all kind of new to me so do what you
think makes most sense.

**Comment by Sobieck00** [comment]
Ok. You could also give me permissions to edit things when I feel like it. But I feel like that would be removing a lot of control from you that I wouldn't like. I sort of like that you can look at what I've done and go your own way if it makes sense to do that without wading through edits of my code.
